---
- name: install automysqlbackup
  apt:
    pkg: automysqlbackup
    state: present
  tags:
    - mysql
    - backups
    - dependencies

- name: copy automyqlbackup config
  template:
    src: etc_default_automysqlbackup.j2
    dest: /etc/default/automysqlbackup
    mode: 0644
  tags:
    - mysql
    - backups
