---
- name: install php
  apt: pkg={{ item }} state=installed
  with_items:
    - php5-cli
    - php5-common
    - php5-curl
    - php5-dev
    - php5-fpm
    - php5-gd
    - php5-mcrypt
    - php5-mysql
    - php5-xmlrpc
    - libssh2-php
  tags:
    - php
    - dependencies

- name: start php5-fpm service
  service:
    name: php5-fpm
    state: started
    enabled: true
  tags:
    - php

- include: composer.yml
