---

- name: install ufw
  apt:
    pkg: ufw
    state: installed
  tags:
    - dependencies
    - firewall

- name: set firewall to deny everything
  ufw:
    policy: deny
  tags: firewall

- name: set firewall rule for ssh traffic
  ufw:
    rule: allow
    port: ssh
    proto: tcp
  tags:
    - firewall
    - ssh

- name: enable ufw
  ufw:
    state: enabled
  tags: firewall
