---

- name: update apt cache
  apt:
    update_cache: yes
  tags: dependencies

- name: upgrade all safe packages
  apt:
    upgrade: safe
  tags: dependencies

- name: install required and nice-to-have packages
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - "{{ required_packages }}"
  tags: dependencies

- include: firewall.yml # Firewall should alway be first.

- include: security.yml
- include: ssh.yml
- include: users.yml
