---

- name: install security-related packages
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - fail2ban
    - whois
    - lynis
    - rkhunter
  tags:
    - dependencies
    - security

- name: ensure fail2ban is started
  service:
    name: fail2ban
    state: started
