---

- name: disallow root ssh access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no" state=present
  notify: restart ssh
  tags: ssh

- name: disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh
  tags: ssh

- name: install mosh for better sshing
  apt:
    pkg: mosh
    state: installed
  tags:
    - dependencies
    - ssh

- name: set firewall rule for mosh
  ufw:
    rule: allow
    port: 60000:61000
    proto: udp
  tags:
    - firewall
    - ssh
