---
- name: create the user accounts
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: present
    shell: /bin/bash
    groups: sudo
    generate_ssh_key: yes
  with_items: "{{ users }}"
  tags: users

- name: add authorized_keys for the user
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', item.public_keys) }}"
  with_items: "{{ users }}"
  tags: users
