---
- name: install and configure the all the servers
  hosts: all
  
  roles:
    - common

- name: setup the db servers
  hosts: db
  
  roles:
    - mysql

- name: setup the web servers
  hosts: web
  
  roles:
    - nginx
    - php
    - sbaerlocher.wp-cli
    - website
