---
- name: create the log directories
  file:
    path: /srv/www/{{ item.domain }}/www/logs
    state: directory
    mode: 0755
  with_items:
    - "{{ websites }}"
  tags:
    - nginx
    - websites

- name: create the html directory
  file:
    path: /srv/www/{{ item.domain }}/www/html
    state: directory
    mode: 0755
    owner: deploy
    group: deploy
  with_items:
    - "{{ websites }}"
  tags:
    - websites

- name: add nginx config
  template:
    src: etc_nginx_site-available_website.j2
    dest: /etc/nginx.sites-available/{{ item.domain }}-www.conf
    owner: root
    group: root
  with_items:
    - "{{ websites }}"
  tags:
    - nginx
    - websites
  notify: reload nginx

- name: enabled nginx config
  file:
    src: /etc/nginx/sites-available/{{ item.domain }}-www.conf
    dest: /etc/nginx/sites-enabled/{{ item.domain }}-www.conf
    state: link
  with_items:
    - "{{ websites }}"
  tags:
    - nginx
    - websites
  notify: reload nginx

- include: db.yml
- include: wp.yml
